# Vartija dev Docker compose
# Copyright 2022 Alberto Morón Hernández
version: '3.8'

services:
  # https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.DownloadingAndRunning.html#docker
  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"
    ports:
      - "8000:8000"
    environment:
      - "TZ=UTC"

  vartija:
    depends_on:
      - dynamodb-local
    links:
      - dynamodb-local
    build:
      context: ../..  # The project root.
      dockerfile: _docker/dev/Dockerfile.vartija.dev  # Relative to 'context'.
    container_name: vartija
    ports:
      - "8080:8080"
    environment:
      - "TZ=UTC"
      - "AWS_DYNAMODB_ENDPOINT=$AWS_DYNAMODB_ENDPOINT"
      - "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
      - "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
      - "AWS_REGION=$AWS_REGION"

networks:
  vartija_net:
    name: vartija_net
    driver: "bridge"
