# Vartija dev Dockerfile
# Copyright 2022 Alberto Morón Hernández
FROM amazon/aws-lambda-python:3.9
# Python 3.9 on Amazon Linux 2.

# [docs.aws.amazon.com/lambda/latest/dg/images-create.html#images-create-from-base]
# LAMBDA_TASK_ROOT == /var/task

WORKDIR "${LAMBDA_TASK_ROOT}"

COPY vartija/*.py "./vartija/"

COPY requirements.txt .
RUN  pip3 install -r requirements.txt

CMD [ "vartija/main.handler" ]